name: Publish Apollo Schema
on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Emit schema
        run: yarn emit-schema

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.23.0-rc.3 | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Publish Schema
        run: rover graph publish ammarahmedca-api-v2@production --schema ./dist/schema.gql
